openapi: 3.1.0
info:
  description: AutoTranslator API
  title: AutoTranslator API
  version: 1.0.0
servers:
- url: https://AutoTranslator
paths:
  /api/translate:
    get:
      operationId: translate
      parameters:
      - explode: true
        in: query
        name: text
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: source
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: target
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      summary: GET api/translate
      x-accepts:
      - '*/*'
components:
  schemas: {}

